//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.SrvsReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsignmentNote.Invoice", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ConsignmentNoteInvoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteProduct[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteSupplier SupplierField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteProduct[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteSupplier Supplier {
            get {
                return this.SupplierField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierField, value) != true)) {
                    this.SupplierField = value;
                    this.RaisePropertyChanged("Supplier");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsignmentNote.Supplier", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ConsignmentNoteSupplier : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteInvoice[] InvoicesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteInvoice[] Invoices {
            get {
                return this.InvoicesField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoicesField, value) != true)) {
                    this.InvoicesField = value;
                    this.RaisePropertyChanged("Invoices");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsignmentNote.Product", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ConsignmentNoteProduct : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteInvoice InvoiceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteSale SaleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Nullable<int> SaleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteInvoice Invoice {
            get {
                return this.InvoiceField;
            }
            set {
                if ((object.ReferenceEquals(this.InvoiceField, value) != true)) {
                    this.InvoiceField = value;
                    this.RaisePropertyChanged("Invoice");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteSale Sale {
            get {
                return this.SaleField;
            }
            set {
                if ((object.ReferenceEquals(this.SaleField, value) != true)) {
                    this.SaleField = value;
                    this.RaisePropertyChanged("Sale");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<int> SaleId {
            get {
                return this.SaleIdField;
            }
            set {
                if ((this.SaleIdField.Equals(value) != true)) {
                    this.SaleIdField = value;
                    this.RaisePropertyChanged("SaleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsignmentNote.Sale", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ConsignmentNoteSale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteCustomer CustomerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ConsignmentNoteProduct[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteCustomer Customer {
            get {
                return this.CustomerField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerField, value) != true)) {
                    this.CustomerField = value;
                    this.RaisePropertyChanged("Customer");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ConsignmentNoteProduct[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((this.SaleDateField.Equals(value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleId {
            get {
                return this.SaleIdField;
            }
            set {
                if ((this.SaleIdField.Equals(value) != true)) {
                    this.SaleIdField = value;
                    this.RaisePropertyChanged("SaleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsignmentNote.Customer", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ConsignmentNoteCustomer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="InvoiceDTO", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class InvoiceDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ProductDTO[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ProductDTO[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ProductDTO", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ProductDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductId {
            get {
                return this.ProductIdField;
            }
            set {
                if ((this.ProductIdField.Equals(value) != true)) {
                    this.ProductIdField = value;
                    this.RaisePropertyChanged("ProductId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductName {
            get {
                return this.ProductNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductNameField, value) != true)) {
                    this.ProductNameField = value;
                    this.RaisePropertyChanged("ProductName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SaleDTO", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class SaleDTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Client.SrvsReference.ProductDTO[] ProductsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Client.SrvsReference.ProductDTO[] Products {
            get {
                return this.ProductsField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductsField, value) != true)) {
                    this.ProductsField = value;
                    this.RaisePropertyChanged("Products");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((this.SaleDateField.Equals(value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleId {
            get {
                return this.SaleIdField;
            }
            set {
                if ((this.SaleIdField.Equals(value) != true)) {
                    this.SaleIdField = value;
                    this.RaisePropertyChanged("SaleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SupplierDto", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class SupplierDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SupplierIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SupplierId {
            get {
                return this.SupplierIdField;
            }
            set {
                if ((this.SupplierIdField.Equals(value) != true)) {
                    this.SupplierIdField = value;
                    this.RaisePropertyChanged("SupplierId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CustomerDto", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class CustomerDto : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int CustomerIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int CustomerId {
            get {
                return this.CustomerIdField;
            }
            set {
                if ((this.CustomerIdField.Equals(value) != true)) {
                    this.CustomerIdField = value;
                    this.RaisePropertyChanged("CustomerId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisplayInvoice", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class DisplayInvoice : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime InvoiceDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int InvoiceIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SupplierNameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime InvoiceDate {
            get {
                return this.InvoiceDateField;
            }
            set {
                if ((this.InvoiceDateField.Equals(value) != true)) {
                    this.InvoiceDateField = value;
                    this.RaisePropertyChanged("InvoiceDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int InvoiceId {
            get {
                return this.InvoiceIdField;
            }
            set {
                if ((this.InvoiceIdField.Equals(value) != true)) {
                    this.InvoiceIdField = value;
                    this.RaisePropertyChanged("InvoiceId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string SupplierName {
            get {
                return this.SupplierNameField;
            }
            set {
                if ((object.ReferenceEquals(this.SupplierNameField, value) != true)) {
                    this.SupplierNameField = value;
                    this.RaisePropertyChanged("SupplierName");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DisplaySale", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class DisplaySale : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CustomerNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime SaleDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SaleIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CustomerName {
            get {
                return this.CustomerNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CustomerNameField, value) != true)) {
                    this.CustomerNameField = value;
                    this.RaisePropertyChanged("CustomerName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime SaleDate {
            get {
                return this.SaleDateField;
            }
            set {
                if ((this.SaleDateField.Equals(value) != true)) {
                    this.SaleDateField = value;
                    this.RaisePropertyChanged("SaleDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SaleId {
            get {
                return this.SaleIdField;
            }
            set {
                if ((this.SaleIdField.Equals(value) != true)) {
                    this.SaleIdField = value;
                    this.RaisePropertyChanged("SaleId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConsignmentNote.ProductOnStock", Namespace="http://schemas.datacontract.org/2004/07/CISStock")]
    [System.SerializableAttribute()]
    public partial class ConsignmentNoteProductOnStock : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int ProductOnStockIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ProductOnStockNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int QuantityField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int ProductOnStockId {
            get {
                return this.ProductOnStockIdField;
            }
            set {
                if ((this.ProductOnStockIdField.Equals(value) != true)) {
                    this.ProductOnStockIdField = value;
                    this.RaisePropertyChanged("ProductOnStockId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ProductOnStockName {
            get {
                return this.ProductOnStockNameField;
            }
            set {
                if ((object.ReferenceEquals(this.ProductOnStockNameField, value) != true)) {
                    this.ProductOnStockNameField = value;
                    this.RaisePropertyChanged("ProductOnStockName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Quantity {
            get {
                return this.QuantityField;
            }
            set {
                if ((this.QuantityField.Equals(value) != true)) {
                    this.QuantityField = value;
                    this.RaisePropertyChanged("Quantity");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SrvsReference.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticateUser", ReplyAction="http://tempuri.org/IService1/AuthenticateUserResponse")]
        bool AuthenticateUser(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AuthenticateUser", ReplyAction="http://tempuri.org/IService1/AuthenticateUserResponse")]
        System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        bool RegisterUser(string username, string password, string firstName, string lastName, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RegisterUser", ReplyAction="http://tempuri.org/IService1/RegisterUserResponse")]
        System.Threading.Tasks.Task<bool> RegisterUserAsync(string username, string password, string firstName, string lastName, string role);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoices", ReplyAction="http://tempuri.org/IService1/GetInvoicesResponse")]
        Client.SrvsReference.ConsignmentNoteInvoice[] GetInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoices", ReplyAction="http://tempuri.org/IService1/GetInvoicesResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteInvoice[]> GetInvoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSupplier", ReplyAction="http://tempuri.org/IService1/DeleteSupplierResponse")]
        bool DeleteSupplier(Client.SrvsReference.ConsignmentNoteSupplier Supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/DeleteSupplier", ReplyAction="http://tempuri.org/IService1/DeleteSupplierResponse")]
        System.Threading.Tasks.Task<bool> DeleteSupplierAsync(Client.SrvsReference.ConsignmentNoteSupplier Supplier);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInvoiceDTO", ReplyAction="http://tempuri.org/IService1/SaveInvoiceDTOResponse")]
        bool SaveInvoiceDTO(Client.SrvsReference.InvoiceDTO invoiceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveInvoiceDTO", ReplyAction="http://tempuri.org/IService1/SaveInvoiceDTOResponse")]
        System.Threading.Tasks.Task<bool> SaveInvoiceDTOAsync(Client.SrvsReference.InvoiceDTO invoiceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSales", ReplyAction="http://tempuri.org/IService1/GetSalesResponse")]
        Client.SrvsReference.ConsignmentNoteSale[] GetSales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSales", ReplyAction="http://tempuri.org/IService1/GetSalesResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteSale[]> GetSalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSaleDTO", ReplyAction="http://tempuri.org/IService1/UpdateSaleDTOResponse")]
        bool UpdateSaleDTO(Client.SrvsReference.SaleDTO updatedSaleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateSaleDTO", ReplyAction="http://tempuri.org/IService1/UpdateSaleDTOResponse")]
        System.Threading.Tasks.Task<bool> UpdateSaleDTOAsync(Client.SrvsReference.SaleDTO updatedSaleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveSaleDTO", ReplyAction="http://tempuri.org/IService1/SaveSaleDTOResponse")]
        bool SaveSaleDTO(Client.SrvsReference.SaleDTO SaleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveSaleDTO", ReplyAction="http://tempuri.org/IService1/SaveSaleDTOResponse")]
        System.Threading.Tasks.Task<bool> SaveSaleDTOAsync(Client.SrvsReference.SaleDTO SaleDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInvoiceDTO", ReplyAction="http://tempuri.org/IService1/UpdateInvoiceDTOResponse")]
        bool UpdateInvoiceDTO(Client.SrvsReference.InvoiceDTO updatedInvoiceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/UpdateInvoiceDTO", ReplyAction="http://tempuri.org/IService1/UpdateInvoiceDTOResponse")]
        System.Threading.Tasks.Task<bool> UpdateInvoiceDTOAsync(Client.SrvsReference.InvoiceDTO updatedInvoiceDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuppliers", ReplyAction="http://tempuri.org/IService1/GetSuppliersResponse")]
        Client.SrvsReference.ConsignmentNoteSupplier[] GetSuppliers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSuppliers", ReplyAction="http://tempuri.org/IService1/GetSuppliersResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteSupplier[]> GetSuppliersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveSupplier", ReplyAction="http://tempuri.org/IService1/SaveSupplierResponse")]
        bool SaveSupplier(Client.SrvsReference.SupplierDto supplierDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveSupplier", ReplyAction="http://tempuri.org/IService1/SaveSupplierResponse")]
        System.Threading.Tasks.Task<bool> SaveSupplierAsync(Client.SrvsReference.SupplierDto supplierDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCustomer", ReplyAction="http://tempuri.org/IService1/SaveCustomerResponse")]
        bool SaveCustomer(Client.SrvsReference.CustomerDto сustomerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/SaveCustomer", ReplyAction="http://tempuri.org/IService1/SaveCustomerResponse")]
        System.Threading.Tasks.Task<bool> SaveCustomerAsync(Client.SrvsReference.CustomerDto сustomerDto);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        Client.SrvsReference.ConsignmentNoteCustomer[] GetCustomers();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetCustomers", ReplyAction="http://tempuri.org/IService1/GetCustomersResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteCustomer[]> GetCustomersAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDisplayInvoices", ReplyAction="http://tempuri.org/IService1/GetDisplayInvoicesResponse")]
        Client.SrvsReference.DisplayInvoice[] GetDisplayInvoices();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDisplayInvoices", ReplyAction="http://tempuri.org/IService1/GetDisplayInvoicesResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.DisplayInvoice[]> GetDisplayInvoicesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceDTOById", ReplyAction="http://tempuri.org/IService1/GetInvoiceDTOByIdResponse")]
        Client.SrvsReference.InvoiceDTO GetInvoiceDTOById(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetInvoiceDTOById", ReplyAction="http://tempuri.org/IService1/GetInvoiceDTOByIdResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.InvoiceDTO> GetInvoiceDTOByIdAsync(int invoiceId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDisplaySales", ReplyAction="http://tempuri.org/IService1/GetDisplaySalesResponse")]
        Client.SrvsReference.DisplaySale[] GetDisplaySales();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDisplaySales", ReplyAction="http://tempuri.org/IService1/GetDisplaySalesResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.DisplaySale[]> GetDisplaySalesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSaleDTOById", ReplyAction="http://tempuri.org/IService1/GetSaleDTOByIdResponse")]
        Client.SrvsReference.SaleDTO GetSaleDTOById(int saleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetSaleDTOById", ReplyAction="http://tempuri.org/IService1/GetSaleDTOByIdResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.SaleDTO> GetSaleDTOByIdAsync(int saleId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateProductOnStock", ReplyAction="http://tempuri.org/IService1/AddOrUpdateProductOnStockResponse")]
        bool AddOrUpdateProductOnStock(Client.SrvsReference.ProductDTO productDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/AddOrUpdateProductOnStock", ReplyAction="http://tempuri.org/IService1/AddOrUpdateProductOnStockResponse")]
        System.Threading.Tasks.Task<bool> AddOrUpdateProductOnStockAsync(Client.SrvsReference.ProductDTO productDTO);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveProductFromStock", ReplyAction="http://tempuri.org/IService1/RemoveProductFromStockResponse")]
        bool RemoveProductFromStock(string productOnStockName, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/RemoveProductFromStock", ReplyAction="http://tempuri.org/IService1/RemoveProductFromStockResponse")]
        System.Threading.Tasks.Task<bool> RemoveProductFromStockAsync(string productOnStockName, int quantity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsOnStock", ReplyAction="http://tempuri.org/IService1/GetProductsOnStockResponse")]
        Client.SrvsReference.ConsignmentNoteProductOnStock[] GetProductsOnStock();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetProductsOnStock", ReplyAction="http://tempuri.org/IService1/GetProductsOnStockResponse")]
        System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteProductOnStock[]> GetProductsOnStockAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : Client.SrvsReference.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<Client.SrvsReference.IService1>, Client.SrvsReference.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool AuthenticateUser(string username, string password) {
            return base.Channel.AuthenticateUser(username, password);
        }
        
        public System.Threading.Tasks.Task<bool> AuthenticateUserAsync(string username, string password) {
            return base.Channel.AuthenticateUserAsync(username, password);
        }
        
        public bool RegisterUser(string username, string password, string firstName, string lastName, string role) {
            return base.Channel.RegisterUser(username, password, firstName, lastName, role);
        }
        
        public System.Threading.Tasks.Task<bool> RegisterUserAsync(string username, string password, string firstName, string lastName, string role) {
            return base.Channel.RegisterUserAsync(username, password, firstName, lastName, role);
        }
        
        public Client.SrvsReference.ConsignmentNoteInvoice[] GetInvoices() {
            return base.Channel.GetInvoices();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteInvoice[]> GetInvoicesAsync() {
            return base.Channel.GetInvoicesAsync();
        }
        
        public bool DeleteSupplier(Client.SrvsReference.ConsignmentNoteSupplier Supplier) {
            return base.Channel.DeleteSupplier(Supplier);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteSupplierAsync(Client.SrvsReference.ConsignmentNoteSupplier Supplier) {
            return base.Channel.DeleteSupplierAsync(Supplier);
        }
        
        public bool SaveInvoiceDTO(Client.SrvsReference.InvoiceDTO invoiceDTO) {
            return base.Channel.SaveInvoiceDTO(invoiceDTO);
        }
        
        public System.Threading.Tasks.Task<bool> SaveInvoiceDTOAsync(Client.SrvsReference.InvoiceDTO invoiceDTO) {
            return base.Channel.SaveInvoiceDTOAsync(invoiceDTO);
        }
        
        public Client.SrvsReference.ConsignmentNoteSale[] GetSales() {
            return base.Channel.GetSales();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteSale[]> GetSalesAsync() {
            return base.Channel.GetSalesAsync();
        }
        
        public bool UpdateSaleDTO(Client.SrvsReference.SaleDTO updatedSaleDTO) {
            return base.Channel.UpdateSaleDTO(updatedSaleDTO);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateSaleDTOAsync(Client.SrvsReference.SaleDTO updatedSaleDTO) {
            return base.Channel.UpdateSaleDTOAsync(updatedSaleDTO);
        }
        
        public bool SaveSaleDTO(Client.SrvsReference.SaleDTO SaleDTO) {
            return base.Channel.SaveSaleDTO(SaleDTO);
        }
        
        public System.Threading.Tasks.Task<bool> SaveSaleDTOAsync(Client.SrvsReference.SaleDTO SaleDTO) {
            return base.Channel.SaveSaleDTOAsync(SaleDTO);
        }
        
        public bool UpdateInvoiceDTO(Client.SrvsReference.InvoiceDTO updatedInvoiceDTO) {
            return base.Channel.UpdateInvoiceDTO(updatedInvoiceDTO);
        }
        
        public System.Threading.Tasks.Task<bool> UpdateInvoiceDTOAsync(Client.SrvsReference.InvoiceDTO updatedInvoiceDTO) {
            return base.Channel.UpdateInvoiceDTOAsync(updatedInvoiceDTO);
        }
        
        public Client.SrvsReference.ConsignmentNoteSupplier[] GetSuppliers() {
            return base.Channel.GetSuppliers();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteSupplier[]> GetSuppliersAsync() {
            return base.Channel.GetSuppliersAsync();
        }
        
        public bool SaveSupplier(Client.SrvsReference.SupplierDto supplierDto) {
            return base.Channel.SaveSupplier(supplierDto);
        }
        
        public System.Threading.Tasks.Task<bool> SaveSupplierAsync(Client.SrvsReference.SupplierDto supplierDto) {
            return base.Channel.SaveSupplierAsync(supplierDto);
        }
        
        public bool SaveCustomer(Client.SrvsReference.CustomerDto сustomerDto) {
            return base.Channel.SaveCustomer(сustomerDto);
        }
        
        public System.Threading.Tasks.Task<bool> SaveCustomerAsync(Client.SrvsReference.CustomerDto сustomerDto) {
            return base.Channel.SaveCustomerAsync(сustomerDto);
        }
        
        public Client.SrvsReference.ConsignmentNoteCustomer[] GetCustomers() {
            return base.Channel.GetCustomers();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteCustomer[]> GetCustomersAsync() {
            return base.Channel.GetCustomersAsync();
        }
        
        public Client.SrvsReference.DisplayInvoice[] GetDisplayInvoices() {
            return base.Channel.GetDisplayInvoices();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.DisplayInvoice[]> GetDisplayInvoicesAsync() {
            return base.Channel.GetDisplayInvoicesAsync();
        }
        
        public Client.SrvsReference.InvoiceDTO GetInvoiceDTOById(int invoiceId) {
            return base.Channel.GetInvoiceDTOById(invoiceId);
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.InvoiceDTO> GetInvoiceDTOByIdAsync(int invoiceId) {
            return base.Channel.GetInvoiceDTOByIdAsync(invoiceId);
        }
        
        public Client.SrvsReference.DisplaySale[] GetDisplaySales() {
            return base.Channel.GetDisplaySales();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.DisplaySale[]> GetDisplaySalesAsync() {
            return base.Channel.GetDisplaySalesAsync();
        }
        
        public Client.SrvsReference.SaleDTO GetSaleDTOById(int saleId) {
            return base.Channel.GetSaleDTOById(saleId);
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.SaleDTO> GetSaleDTOByIdAsync(int saleId) {
            return base.Channel.GetSaleDTOByIdAsync(saleId);
        }
        
        public bool AddOrUpdateProductOnStock(Client.SrvsReference.ProductDTO productDTO) {
            return base.Channel.AddOrUpdateProductOnStock(productDTO);
        }
        
        public System.Threading.Tasks.Task<bool> AddOrUpdateProductOnStockAsync(Client.SrvsReference.ProductDTO productDTO) {
            return base.Channel.AddOrUpdateProductOnStockAsync(productDTO);
        }
        
        public bool RemoveProductFromStock(string productOnStockName, int quantity) {
            return base.Channel.RemoveProductFromStock(productOnStockName, quantity);
        }
        
        public System.Threading.Tasks.Task<bool> RemoveProductFromStockAsync(string productOnStockName, int quantity) {
            return base.Channel.RemoveProductFromStockAsync(productOnStockName, quantity);
        }
        
        public Client.SrvsReference.ConsignmentNoteProductOnStock[] GetProductsOnStock() {
            return base.Channel.GetProductsOnStock();
        }
        
        public System.Threading.Tasks.Task<Client.SrvsReference.ConsignmentNoteProductOnStock[]> GetProductsOnStockAsync() {
            return base.Channel.GetProductsOnStockAsync();
        }
    }
}
